name: autofix.ci

on:
  pull_request:
    branches:
      - main

jobs:
  autofix:
    name: autofix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Yarn Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install Dependencies
        run: yarn install

      - name: ESLint
        run: |
          changed_files=$(git diff --name-only --diff-filter=ACMRUXB origin/main)

          if [ -z "$changed_files" ]; then
            echo "No changed files to lint."
          elif echo "$changed_files" | grep -q "^\.eslintrc\.json$|^\.eslintignore$"; then
            yarn lint:fix
          else
            echo "$changed_files" | grep -E "(.js$|.jsx$|.ts$|.tsx$)" | xargs -r yarn lint:fix
          fi

      - name: Prettier
        run: |
          changed_files=$(git diff --name-only --diff-filter=ACMRUXB origin/main)

          if [ -z "$changed_files" ]; then
            echo "No changed files to format."
          elif echo "$changed_files" | grep -q -E "^\.prettierrc$|^\.prettierignore$"; then
            yarn prettier --write .
          else
            echo "$changed_files" | xargs -r yarn prettier --write --ignore-unknown
          fi

      - name: Apply fixes
        uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
        with:
          commit-message: 'ci: apply automated fixes'
